wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/114/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AltaLangaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/117/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AmaronedellaValpolicellaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/130/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BagnoliFriularoFriularodiBagnoliDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/143/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AstiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/144/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BarberadAstiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/198/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BarbarescoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/200/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BaroloDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/202/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BrunellodiMontalcinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/203/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CannellinodiFrascatiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/216/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CarmignanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/217/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CasteldelMonteBombinoNeroDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/218/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CasteldelMonteNerodiTroiaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/220/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CasteldelMonteRossoRiservaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/221/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CesanesedelPiglioPiglioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/227/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliBolognesiClassicoPignolettoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/228/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliEuganeiFiordArancioFiordAran.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/230/mapOpenData --quiet -O  ../WineRegionMaps/Italy/DoglianiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/231/mapOpenData --quiet -O  ../WineRegionMaps/Italy/DolcettodiDianodAlbaDianodAlbaDO.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/232/mapOpenData --quiet -O  ../WineRegionMaps/Italy/DolcettodiOvadaSuperioreOvadaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/233/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AleaticoPassitodellElbaElbaAleatico.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/365/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CaccemmittediLuceraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/372/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CagliariDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/373/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CalossoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/376/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CampiFlegreiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/377/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CampidanodiTerralbaTerralbaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/382/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CannonaudiSardegnaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/385/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CapriDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/386/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RubinodiCantavennaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/389/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SalaparutaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/392/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SaliceSalentinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/395/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SambucadiSiciliaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/419/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CaremaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/422/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CasavecchiadiPontelatoneDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/425/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CasteggioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/427/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CastelliRomaniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/430/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FianodiAvellinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/431/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FranciacortaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/432/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FrascatiSuperioreDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/434/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GattinaraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/436/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CortesediGaviGaviDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/437/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GhemmeDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/439/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GrecodiTufoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/442/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontecuccoSangioveseDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/443/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontefalcoSagrantinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/447/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MorellinodiScansanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/476/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OffidaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/477/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RamandoloDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/478/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ReciotodiGambellaraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/479/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RomagnaAlbanaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/480/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RosazzoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/482/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ScanzoMoscatodiScanzoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/483/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SforzatodiValtellinaSfursatdiValtel.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/484/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SuveretoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/485/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TorgianoRossoRiservaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/486/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RossodellaValdiCorniaValdiCornia.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/488/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValtellinaSuperioreDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/489/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VerdicchiodiMatelicaRiservaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/490/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VernacciadiSanGimignanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/491/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VernacciadiSerrapetronaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/552/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RossoPicenoPicenoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/553/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SanColombanoSanColombanoalLambroDO.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/554/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SanSeveroDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/555/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SanTorpDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/556/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SanguediGiudaSanguediGiudadellOlt.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/557/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SannioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/558/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SantaMargheritadiBeliceDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/559/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SAnnadiIsolaCapoRizzutoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/560/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SavutoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/561/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ScavignaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/562/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SciaccaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/563/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SerrapetronaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/568/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CastellerDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/569/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontelloMontelloRossoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/573/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OltrepPaveseDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/577/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PrimitivodiManduriaDolceNaturaleDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/578/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ReciotodellaValpolicellaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/579/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ReciotodiSoaveDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/580/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RoeroDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/582/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SoaveSuperioreDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/583/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TaurasiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/584/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VermentinodiGalluraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/601/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CanaveseDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/621/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AbruzzoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/624/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AglianicodelVultureDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/625/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AlbugnanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/626/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CandiadeiColliApuaniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/627/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CapalbioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/628/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CaprianodelColleDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/629/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AlbaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/631/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CellaticaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/632/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AffileCesanesediAffileDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/633/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CesanesediOlevanoRomanoOlevanoRoman.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/634/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CinqueTerreCinqueTerreSciacchetrDO.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/635/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CisternadAstiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/636/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliAlbaniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/637/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidiFaenzaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/638/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliLanuviniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/639/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollinediLevantoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/651/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CerasuolodAbruzzoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/652/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CilentoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/653/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidellaSabinaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/654/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CopertinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/655/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CoriDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/656/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CortesedellAltoMonferratoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/658/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CostadAmalfiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/659/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CostedellaSesiaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/661/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CurtefrancaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/662/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AglianicodelTaburnoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/663/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AglianicodelVultureSuperioreDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/664/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AlcamoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/665/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AversaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/667/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AleaticodiGradoliDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/668/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BarberadAlbaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/669/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BarberadelMonferratoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/672/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AleaticodiPugliaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/673/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AlezioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/676/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AlgheroDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/677/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AnsonicaCostadellArgentarioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/678/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BarcoRealediCarmignanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/679/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AmeliaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/681/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ApriliaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/682/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BarlettaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/683/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ArboreaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/684/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BianchellodelMetauroDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/685/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BiancoCapenaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/686/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BiancodellEmpoleseDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/687/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ArcoleDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/688/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliBericiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/689/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FalerioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/690/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AssisiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/691/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliBolognesiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/692/mapOpenData --quiet -O  ../WineRegionMaps/Italy/Est!Est!!Est!!!diMontefiasconeDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/693/mapOpenData --quiet -O  ../WineRegionMaps/Italy/EsinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/694/mapOpenData --quiet -O  ../WineRegionMaps/Italy/EloroDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/695/mapOpenData --quiet -O  ../WineRegionMaps/Italy/DolcettodiOvadaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/696/mapOpenData --quiet -O  ../WineRegionMaps/Italy/DolcettodAlbaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/699/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SiracusaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/700/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliRomagnaCentraleDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/701/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidelTrasimenoTrasimenoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/703/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidiScandianoediCanossaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/704/mapOpenData --quiet -O  ../WineRegionMaps/Italy/DolcettodAcquiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/705/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ErbalucediCalusoCalusoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/706/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliEtruschiViterbesiTusciaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/707/mapOpenData --quiet -O  ../WineRegionMaps/Italy/DolcettodAstiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/709/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AtinaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/710/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliEuganeiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/711/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliMaceratesiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/713/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CarsoCarsoKrasDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/714/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliMartaniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/715/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SizzanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/716/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliPeruginiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/718/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliPesaresiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/719/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliPiacentiniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/721/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CastelSanLorenzoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/723/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CasteldelMonteDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/725/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollineJonicheTarantineDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/726/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BardolinoSuperioreDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/727/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CerveteriDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/728/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollineLucchesiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/729/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollineNovaresiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/730/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VerdicchiodeiCastellidiJesiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/731/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollineSaluzzesiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/732/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollioGorizianoCollioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/734/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ConteadiSclafaniValledolmoConteadi.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/735/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ChiantiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/736/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AsoloProseccoColliAsolaniProsecc.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/737/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SpoletoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/738/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SquinzanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/739/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FalernodelMassicoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/740/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidiConeglianoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/741/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CneroDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/742/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FaraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/753/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CirceoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/754/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliAltotiberiniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/755/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidellEtruriaCentraleDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/757/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidImolaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/758/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidiParmaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/760/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidiRiminiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/761/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ChiantiClassicoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/762/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FalanghinadelSannioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/766/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FrascatiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/767/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FaroDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/768/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FreisadAstiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/769/mapOpenData --quiet -O  ../WineRegionMaps/Italy/NettunoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/771/mapOpenData --quiet -O  ../WineRegionMaps/Italy/NotoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/772/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BrindisiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/775/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ContessaEntellinaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/776/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ControguerraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/778/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CortiBenedettinedelPadovanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/780/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LameziaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/781/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CortonaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/786/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FreisadiChieriDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/789/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GabianoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/790/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AltoAdigeSdtirolSdtirolerdell.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/793/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GalluccioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/794/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BagnoliBagnolidiSopraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/795/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GambellaraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/796/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GenazzanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/797/mapOpenData --quiet -O  ../WineRegionMaps/Italy/DeliaNivolelliDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/798/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OrciaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/800/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ElbaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/801/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OrtaNovaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/802/mapOpenData --quiet -O  ../WineRegionMaps/Italy/EriceDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/803/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OrtonaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/805/mapOpenData --quiet -O  ../WineRegionMaps/Italy/EtnaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/806/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OrtrugodeiColliPiacentiniOrtrugoC.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/807/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BardolinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/809/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GioiadelColleDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/811/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FriuliAquileiaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/812/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OstuniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/813/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BiancodiCustozaCustozaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/814/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FriuliColliOrientaliDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/815/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PantelleriaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/816/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ParrinaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/817/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BiancodiPitiglianoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/818/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PenisolaSorrentinaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/819/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FriuliGraveDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/820/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PentroPentrodiIserniaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/822/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FriuliIsonzoIsonzodelFriuliDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/823/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BifernoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/824/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GirdiCagliariDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/825/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FriuliLatisanaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/826/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PergolaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/827/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GalatinaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/828/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GardaColliMantovaniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/829/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PiaveDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/830/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BivongiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/832/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GolfodelTigullioPortofinoPortofino.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/833/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GranceSenesiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/834/mapOpenData --quiet -O  ../WineRegionMaps/Italy/IrpiniaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/835/mapOpenData --quiet -O  ../WineRegionMaps/Italy/StreviDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/836/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TavoliereTavolieredellePuglieDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/837/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerradOtrantoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/838/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerredellAltaValdAgriDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/839/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerracinaMoscatodiTerracinaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/840/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerreAlfieriDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/841/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerrediCasoleDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/842/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerraticodiBibbonaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/843/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TorgianoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/844/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerreTollesiTullumDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/845/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValdArbiaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/846/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValdArnodiSopraValdarnodiSopraDO.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/847/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValcalepioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/850/mapOpenData --quiet -O  ../WineRegionMaps/Italy/IschiaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/852/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LessonaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/853/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PineroleseDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/854/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LizzanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/855/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PinotnerodellOltrepPaveseDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/856/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LoazzoloDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/857/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PominoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/858/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LocorotondoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/859/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OrmeascodiPornassioPornassioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/861/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GravinaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/862/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PrimitivodiManduriaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/864/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GrecodiBiancoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/865/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ReggianoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/867/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GrignolinodAstiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/868/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GrignolinodelMonferratoCasaleseDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/869/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerredelColleoniColleoniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/870/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CaldaroKaltererKaltererseeLagodi.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/871/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GrottinodiRoccanovaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/872/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RenoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/873/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LambruscodiSorbaraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/874/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RiesiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/875/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LambruscoGrasparossadiCastelvetroDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/877/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GutturnioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/878/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RivieradelBrentaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/879/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LambruscoMantovanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/880/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GardaBrescianoRivieradelGardaBresci.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/881/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LambruscoSalaminodiSantaCroceDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/882/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ITerrenidiSanseverinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/883/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RivieraligurediPonenteDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/884/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RomaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/885/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LessiniDurelloDurelloLessiniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/886/mapOpenData --quiet -O  ../WineRegionMaps/Italy/DolceacquaRossesediDolceacquaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/887/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LacrimadiMorroLacrimadiMorrodAlba.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/888/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MelissaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/889/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RossoCneroDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/890/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MenfiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/891/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RossodiCerignolaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/892/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MerlaraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/893/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MonicadiSardegnaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/894/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RossodiMontalcinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/895/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MonrealeDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/896/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TintiliadelMoliseDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/897/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontecarloDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/898/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontecompatriColonnaMontecompatriCo.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/899/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontecuccoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/900/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TodiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/901/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValdichianatoscanaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/902/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ModenadiModenaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/903/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MolisedelMoliseDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/904/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MonferratoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/905/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontefalcoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/907/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontelloColliAsolaniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/909/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontepulcianodAbruzzoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/916/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValdinievoleDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/925/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValledAostaValledAosteDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/927/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MonteregiodiMassaMarittimaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/928/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValsusaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/931/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VerdicchiodiMatelicaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/934/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontescudaioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/935/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontiLessiniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/936/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MoscadellodiMontalcinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/937/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MoscatodiSardegnaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/938/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MoscatodiSorsoSennoriMoscatodiSor.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/939/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MoscatodiTraniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/945/mapOpenData --quiet -O  ../WineRegionMaps/Italy/NardDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/946/mapOpenData --quiet -O  ../WineRegionMaps/Italy/NascodiCagliariDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/950/mapOpenData --quiet -O  ../WineRegionMaps/Italy/NebbiolodAlbaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/951/mapOpenData --quiet -O  ../WineRegionMaps/Italy/NegroamarodiTerradOtrantoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/954/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValdiCorniaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/962/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValPolcveraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/969/mapOpenData --quiet -O  ../WineRegionMaps/Italy/NuragusdiCagliariDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/994/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VerdunoPelavergaVerdunoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/996/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VermentinodiSardegnaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/999/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VesuvioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1005/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VicenzaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1008/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VignanelloDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1009/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SerenissimaVignetidellaSerenissimaDO.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1010/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VillamagnaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1011/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VinSantodiCarmignanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1012/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VinSantodelChiantiClassicoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1014/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VittoriaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1015/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ZagaroloDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1016/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BocaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1017/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BolgheriSassicaiaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1019/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BolgheriDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1020/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BonardadellOltrepPaveseDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1023/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BoscoEliceoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1027/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BotticinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1029/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BramaterraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1030/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BreganzeDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1031/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ButtafuocoButtafuocodellOltrepPaves.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1032/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LagodiCorbaraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1033/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LangheDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1034/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LeveranoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1036/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MalvasiadelleLipariDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1037/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MalvasiadiBosaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1038/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MalvasiadiCasorzodAstiCasorzoMal.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1039/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MalvasiadiCastelnuovoDonBoscoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1040/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SanGinesioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1041/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValliOssolaneDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1042/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MamertinoMamertinodiMilazzoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1043/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MandrolisaiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1046/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MarinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1047/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MarsalaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1048/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MartinaMartinaFrancaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1049/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MateraDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1050/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MatinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1052/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SantAntimoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1053/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SiciliaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1055/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TrentoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1059/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerrediCosenzaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1060/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VernacciadiOristanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1061/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SardegnaSemidanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1062/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerrediPisaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1063/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VelletriDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1064/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TrentinoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1065/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollinaTorineseDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1066/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CarignanodelSulcisDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1067/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CirDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1069/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontepulcianodAbruzzoCollineTeramane.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1070/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TarquiniaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1071/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OltrepPavesemetodoclassicoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1072/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TrebbianodAbruzzoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1075/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValtnesiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1076/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FriuliAnniaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1077/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValpolicellaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1078/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SoaveDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1079/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValpolicellaripassoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1081/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SanGimignanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1082/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SovanaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1083/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VeneziaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1087/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OrvietanoRossoRossoOrvietanoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1088/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValtellinarossoRossodiValtellinaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1089/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliOrientalidelFriuliPicolitDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1090/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BarberadelMonferratoSuperioreDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1091/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ConeglianoProseccoConeglianoValdobb.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1093/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MalanottedelPiavePiaveMalanotteDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1112/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VinSantodelChiantiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1113/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerrediOffidaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1114/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OltrepPavesePinotgrigioDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1115/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CastellidiJesiVerdicchioRiservaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1116/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliTortonesiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1118/mapOpenData --quiet -O  ../WineRegionMaps/Italy/NizzaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1146/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BrachettodAcquiAcquiDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1149/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RomagnaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1155/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CerasuolodiVittoriaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1156/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VinoNobilediMontepulcianoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1158/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VinSantodiMontepulcianoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1159/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RossodiMontepulcianoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1160/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TeroldegoRotalianoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1162/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RuchdiCastagnoleMonferratoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1192/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PiemonteDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1203/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MaremmaToscanaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/493/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AltaValledellaGreveIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/941/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LiguriadiLevanteIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/496/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AltoMincioIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/497/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AnagniIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/499/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AvolaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/502/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BarbagiaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/503/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BasilicataIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/504/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BettonaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/506/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CalabriaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/521/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CamarroIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/523/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CampaniaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/524/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CannaraIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/525/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CatalanescadelMonteSommaSommaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/526/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CivitelladAglianoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/588/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ArghillIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/591/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BergamascaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/592/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BiancodiCastelfrancoEmiliaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/593/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliCiminiIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/595/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidelLimbaraIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/743/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BeneventoBeneventanoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/744/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidelSangroIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/745/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidellaToscanacentraleIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/746/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidiSalernoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/747/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollinadelMilaneseIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/748/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollinedelGenovesatoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/749/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollinePescaresiIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/750/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollineSavonesiIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/751/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollineTeatineIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/752/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ConselvanoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/782/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollineFrentaneIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/783/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CostaEtruscoRomanaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/785/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CostaToscanaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/787/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CostaViolaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/788/mapOpenData --quiet -O  ../WineRegionMaps/Italy/DauniaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/791/mapOpenData --quiet -O  ../WineRegionMaps/Italy/DelVasteseHistoniumIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/799/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliTrevigianiIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/804/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BenacoBrescianoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/821/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ColliAprutiniIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/866/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PompeianoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/906/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ProvinciadiMantovaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/908/mapOpenData --quiet -O  ../WineRegionMaps/Italy/DugentaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/910/mapOpenData --quiet -O  ../WineRegionMaps/Italy/EmiliadellEmiliaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/911/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ProvinciadiNuoroIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/913/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ProvinciadiPaviaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/914/mapOpenData --quiet -O  ../WineRegionMaps/Italy/QuistelloIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/915/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FortanadelTaroIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/917/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RoccamonfinaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/918/mapOpenData --quiet -O  ../WineRegionMaps/Italy/EpomeoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/919/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FontanarossadiCerdaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/920/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RomangiaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/921/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RonchidiBresciaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/922/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RonchiVaresiniIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/923/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RotaeIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/924/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SabbionetaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/926/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SalemiIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/930/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ForlIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/932/mapOpenData --quiet -O  ../WineRegionMaps/Italy/FrusinatedelFrusinateIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/933/mapOpenData --quiet -O  ../WineRegionMaps/Italy/IsoladeiNuraghiIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/940/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LazioIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/942/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LipudaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/943/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LocrideIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/944/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MarcaTrevigianaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/947/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MarmillaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/952/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontecastelliIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/953/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MontenettodiBresciaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/957/mapOpenData --quiet -O  ../WineRegionMaps/Italy/NurraIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/958/mapOpenData --quiet -O  ../WineRegionMaps/Italy/NarniIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/959/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OgliastraIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/960/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OscoTerredegliOsciIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/961/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PaestumIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/963/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PalizziIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/965/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ParteollaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/966/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PellaroIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/967/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PlanargiaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/968/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerreLarianeIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/970/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MarcheIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/971/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MurgiaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/972/mapOpenData --quiet -O  ../WineRegionMaps/Italy/PugliaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/973/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RavennaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/974/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SalentoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/975/mapOpenData --quiet -O  ../WineRegionMaps/Italy/RubiconeIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/976/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TharrosIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/977/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ToscanoToscanaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/978/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TrexentaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/979/mapOpenData --quiet -O  ../WineRegionMaps/Italy/UmbriaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/980/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValdiMagraIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/981/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValdiNetoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/982/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValTidoneIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/983/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValcamonicaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/984/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValdamatoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/986/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValleBeliceIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/987/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValledelTirsoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/989/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValledItriaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/990/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VallidiPortoPinoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/991/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VenetoorientaleIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/992/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SalinaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/993/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ScillaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/995/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SebinoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/997/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SibiolaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/998/mapOpenData --quiet -O  ../WineRegionMaps/Italy/BiancodelSillaroSillaroIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1000/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VenetoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1002/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VeneziaGiuliaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1003/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerredelVolturnoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1004/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VeronaVeroneseProvinciadiVeronaIG.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1006/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SpelloIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1021/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TarantinoIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1022/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerrazzedellImperieseIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1024/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerreAquilaneTerredeLAquilaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1025/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerrediChietiIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1026/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerrediVelejaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1094/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerreSicilianeIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1095/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AlleronaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1154/mapOpenData --quiet -O  ../WineRegionMaps/Italy/MitterbergIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1176/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AlpiReticheIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/440/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LisonDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/657/mapOpenData --quiet -O  ../WineRegionMaps/Italy/CollidiLuniDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/810/mapOpenData --quiet -O  ../WineRegionMaps/Italy/OrvietoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/831/mapOpenData --quiet -O  ../WineRegionMaps/Italy/GardaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/848/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TerradeifortiValdadigeTerradeifortiDO.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/860/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LuganaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/964/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ValdadigeEtschtalerDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1035/mapOpenData --quiet -O  ../WineRegionMaps/Italy/LisonPramaggioreDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1051/mapOpenData --quiet -O  ../WineRegionMaps/Italy/SanMartinodellaBattagliaDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1129/mapOpenData --quiet -O  ../WineRegionMaps/Italy/ProseccoDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/586/mapOpenData --quiet -O  ../WineRegionMaps/Italy/AltoLivenzaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/988/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VallagarinaIGP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1007/mapOpenData --quiet -O  ../WineRegionMaps/Italy/VignetidelleDolomitiWeinbergDolomite.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1182/mapOpenData --quiet -O  ../WineRegionMaps/Italy/delleVenezieBenekihokolievDOP.geojson &
wget https://dopigp.politicheagricole.gov.it/bedopigp/v1/disciplinari/1175/mapOpenData --quiet -O  ../WineRegionMaps/Italy/TrevenezieTriBeneijeIGP.geojson &
